### ISSUE TITLE
twitter: allow auth via users' browser

### ISSUE THREAD

**Issue by dingens** [satanas/Turpial#307]
There's plenty of cases where it's annoying to need to use the inline browser in the auth window (the one that appears upon account creation).
Examples: user is already logged in in the browser (need to re-login), user does not know the password but uses a password manager in form of a browser plugin (need to copy the password around), user has a proxy configured, …

So I suggest to just open the user's browser instead of using that inline browser thing, and put a little popup that automatically stays on top of the other windows in front of the browser where the user enters the pin.
If you like to keep the inline browser, I suggest putting a little link to open the auth page in the user's browser to give users the choice.

**Comment by satanas** [comment]
I can't just open the authorization page in the user's web browser (and remove the oauth window) because webbrowser module in Python (the one used to open links) only works with a few browsers (Chrome and Firefox AFAIR) and people that use any other browser couldn't open this page to authorize the app. It happened a long time ago.

I could add the button/link to allow the user open the auth page with his/her browser for the cases you mentioned, that would be a nice option. Thanks for the suggestion

**Comment by satanas** [comment]
Implemented button to open authorization page in user browser
