### ISSUE TITLE
Using your repo = latest version?

### ISSUE THREAD

**Issue by PartisanEntity** [satanas/Turpial#342]
Hi there, 

I would like to install the latest version of Turpial.
1. On this page ( http://turpial.org.ve/downloads/ ) it still says "Saucy Salamander", is this ppa not compatible with Ubuntu 14.04?
2. Also, if I use this ppa, will I always have the latest available version?

Thanks

**Comment by satanas** [comment]
Hello @PartisanEntity,

The PPA for Turpial is not compatible with Ubuntu 14.04 yet. Here you can see which Ubuntu versions are supported by the moment https://launchpad.net/~effie-jayx/+archive/turpial.

That PPA doesn't has the latest version, to have the latest version I recommend you to install the development version. Follow the steps on the wiki in order to do that http://wiki.turpial.org.ve/dev:installation.

Regards
