### ISSUE TITLE
Recover turpial.org.ve

### ISSUE THREAD

**Issue by X3MBoy** [satanas/Turpial#403]
Site is down, I couldn't check why. Probably domain issues.

**Comment by Richzendy** [comment]
Hi! 

The site was a wordpress installed on a VM from canaima project but because a not clear reason, the VM was down and all site was lost.

I'm speaking with @satanas the last days to make some work to get the site alive again but without dependencies (hosting, vm, etc), the logic way is to have a static site on github-pages.

I'm have a few work here (jekyll based)  https://richzendy.github.io/Turpial-Website/ (with a old backup the all blog posts was restored) waiting to a clone by @satanas and waiting to @satanas domain setup.

If you want to make any contribution, any help can be appreciated.

**Comment by satanas** [comment]
http://turpial.org.ve/ is up & running again. In the next days, I'll be working on the missing content.

Thanks to @Richzendy for the help with the DNS setup and stuff 👍
